module.exports = {
  RECTANGLE: 1,
  SQUARE: 2,
  CIRCLE: 3,
  TORUS: 4,
  SPHERE: 5,
  gravity: 60,
  wavespeed: 20,
  minVelocity: 10,
  maxVelocity: 50,
  background: 0xffd1dc,
  ambientColor: 0xffffff,
  ambientIntensity: 0.1,
  directionalColor: 0xffffff,
  directionalIntensity: 1,
  blockColor: 0xffffff,
  blockHeight: 2,
  timeScale: 20,
  squareSide: 1,
  circleRadius: 1,
  sphereRadius: 1,
  torusRadius: 1,
  torusTube: 0.3,
  shape: 1,
  vibration: true,
}