module.exports = {
  RECTANGLE: 1,
  SQUARE: 2,
  CIRCLE: 3,
  TORUS: 4,
  SPHERE: 5,
  gravity: 60,
  wavespeed: 20,
  minVelocity: -1,
  maxVelocity: -1,
  background: '#ffd1dc',
  ambientColor: '#ffffff',
  ambientIntensity: 0.1,
  directionalColor: '#ffffff',
  directionalIntensity: 1,
  blockColor: '#ffffff',
  // lerpBlockColor: '#000000',
  blockHeight: 2,
  timeScale: 20,
  squareSide: 1,
  circleRadius: 1,
  sphereRadius: 1,
  torusRadius: 1,
  torusTube: 0.3,
  shape: 1,
  vibration: true,
}